version: '3'

# Containers we're going to run.
services:
  # Our Phoenix container.
  app:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory.
      context: .
    environment:
      # Variables to connect to our Postgres server.
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: wl_development
      PGPORT: 5432
      PGHOST: db
      MIX_ENV: dev

    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container.
      - 4000:4000
    # depends_on:
      # The DB container needs to be started before we start this container.
      # - db
    links:
      - db
  db:
    # We use the predefined Postgres image.
    image: postgres:15.2-alpine3.17
    environment:
      # Set user/password for Postgres.
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data.
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes.
volumes:
  pgdata:
