FROM elixir:1.17.2-otp-27-alpine

RUN apk update && \
  apk add postgresql-client inotify-tools && \
  apk add g++ && apk add make && \
  apk add --update nodejs npm
# Create app directory and copy the Elixir projects into it.
RUN mkdir -p /app
WORKDIR /app


# Install Hex package manager.
# By using `--force`, we don’t need to type “Y” to confirm the installation.
RUN mix local.rebar --force && \
  mix local.hex --force && \
  mix archive.install --force hex phx_new

COPY mix.exs .
COPY mix.lock .

# Compile the project.
RUN mix deps.clean --all && \
  mix deps.get && mix deps.compile

COPY assets ./assets
WORKDIR /app/assets
# RUN npm installk

WORKDIR /app

COPY config ./config
COPY lib ./lib
COPY priv ./priv
COPY test ./test
COPY entrypoint.dev.sh ./entrypoint.sh

RUN mix do compile

RUN chmod +x /app/entrypoint.sh
# ENV ENV="/etc/profile"
EXPOSE 4000
ENTRYPOINT [ "/app/entrypoint.sh" ]
